### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Franco-Mateo-Gomez** [UrielBlanco7/tienda-mercado-uriel#1]
**Propuestas de mejora**

1 - Footer = En la versión Desktop faltó un poco más de espaciado entre los párrafos (quizás unos 5 o 10 px de padding).
![image](https://user-images.githubusercontent.com/88519148/218476264-c15d9ab0-a091-4297-90fc-e25db93dc3a4.png)

2- Centrar los elementos del header verticalmente.
![image](https://user-images.githubusercontent.com/88519148/218476799-47e0b973-e1fc-4b0a-bb7c-fe07641515ad.png)

**Comentarios**

Me gustó los estilos aplicados en los formularios de registro y login.

**Comment by UrielBlanco7** [comment]
Espacioado aplicado y resuelto.

**Comment by UrielBlanco7** [comment]
> **Propuestas de mejora**
> 
> 1 - Footer = En la versión Desktop faltó un poco más de espaciado entre los párrafos (quizás unos 5 o 10 px de padding). ![image](https://user-images.githubusercontent.com/88519148/218476264-c15d9ab0-a091-4297-90fc-e25db93dc3a4.png)
> 
> 2- Centrar los elementos del header verticalmente. ![image](https://user-images.githubusercontent.com/88519148/218476799-47e0b973-e1fc-4b0a-bb7c-fe07641515ad.png)
> 
> **Comentarios**
> 
> Me gustó los estilos aplicados en los formularios de re
