### ISSUE TITLE
correccion

### ISSUE THREAD

**Issue by alexito2960** [UrielBlanco7/tienda-mercado-uriel#2]
HEADER:

● Logo = bien el tamaño todo 

● Barra de búsqueda = la barra de busqueda para dispositivos desktop esta bien le podes poner una lupita al lado o como prefieras y para los moviles le podes hacer un poco mas chica  y que  se ponga al lado del logo te va a quedar god.

● Comprá en cuotas y sin tarjeta de crédito = a este la fuente lo podes hacer mas chica podes ponerle 16px o 10px como más te guste o vas probando o fijate si lo tenes en una etiqueta <p></p> lo pones ahi asi se te hace mas chico o se te acomoda mejor como a vos te guste pero en realidad esta bien asi pero por ahi te queda mucho mejor asi.

● Barra de navegación: eso esta todo re bien tipo cumple todo le podes poner un poco mas de estilo de ultima centrarlos agregarle algun color de fondo y ahi asi o lo dejas asi que en teoria estaria bien solo es más diseño no mas
● Ofertas
● Tiendas Oficiales
● Vender
● Ayuda
● Login
● Registro
● Mis compras

MAIN:

En esos dos esta todo bien lo que le podrias agregar es centrar un poco mas los descuentos y que se muevan mas al final de su contenedor lo podes hacer con un text-aling o con un position eso depende de tu html, podrias agregar que las trancisiones de los productos sea más lentas asi se hacen más despacio lo del carrito y la sombra tambien cuando aparece el nombre del producto

● Sección basada en las últimas visitas
● Sección de ofertas

FOOTER:
 
A estos 4 los centraria mejor y que esten mas juntos y que los logos cambien de color cuando pases el mouse por ellos, el color de la tipografia le podes poner un gris más oscuro para que convine con el gris más claro, podes ponerlo dentro de una etiqueta <article></article> asi se ponen más mas juntos y les queda un margen probalo por ahi te gusta si no lo dejas como esta. 

● Pagá con tarjeta o en efectivo
● Envío gratis desde $ 2.500
● Seguridad, de principio a fin
● Copyright © 1999-2022 MercadoLiebre S.R.L.

2. Haciendo foco en los estilos del pie de página (Footer):
● ¿El contenido de todos los artículos está centrado? = centralos un toque más y te queda god

● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles? = el icono si te falta el margen inferior no más

3. ¿El sitio se adapta a distintas resoluciones de pantalla? = si se adapta bro solo tenes que agregare un poco más de estilo no más
4. ¿El sitio cuenta con un formulario de registro de usuarios? = si
5. ¿El sitio cuenta con un formulario de login?  = si

6. ¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios? = si

7. ¿El search bar es un formulario?

9. ¿Se utilizan animaciones y propiedades de transición de CSS? = algo si solo agregale a los productos y botenes de los formularios

11. Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien = toda la estructura esta bien bro solo te falta un poco mas de diseño, posicionamientos y estas.

12.Por último, menciona algo que tu compañero podría mejorar = ya esta todo

**Comment by UrielBlanco7** [comment]
> HEADER:
> 
> ● Logo = bien el tamaño todo
> 
> ● Barra de búsqueda = la barra de busqueda para dispositivos desktop esta bien le podes poner una lupita al lado o como prefieras y para los moviles le podes hacer un poco mas chica y que se ponga al lado del logo te va a quedar god.
> 
> ● Comprá en cuotas y sin tarjeta de crédito = a este la fuente lo podes hacer mas chica podes ponerle 16px o 10px como más te guste o vas probando o fijate si lo tenes en una etiqueta
> 
> lo pones ahi asi se te hace mas chico o se te acomoda mejor como a vos te guste pero en realidad esta bien asi pero por ahi te queda mucho mejor asi.
> ● Barra de navegación: eso esta todo re bien tipo cumple todo le podes poner un poco mas de estilo de ultima centrarlos agregarle algun color de fondo y ahi asi o lo dejas asi que en teoria estaria bien solo es más diseño no mas ● Ofertas ● Tiendas Oficiales ● Vender ● Ayuda ● Login ● Registro ● Mis compras
> 
> MAIN:
> 
> En esos dos esta todo bien lo que le podrias agregar es centrar un poco mas los descuentos y que se muevan mas al final de su contenedor lo podes hacer con un text-aling o con un position eso depende de tu html, podrias agregar que las trancisiones de los productos sea más lentas asi se hacen más despacio lo del carrito y la sombra tambien cuando aparece el nombre del producto
> 
> ● Sección basada en las últimas visitas ● Sección de ofertas
> 
> FOOTER:
> 
> A estos 4 los centraria mejor y que esten mas juntos y que los logos cambien de color cuando pases el mouse por ellos, el color de la tipografia le podes poner un gris más oscuro para que convine con el gris más claro, podes ponerlo dentro de una etiqueta
> 
> asi se ponen más mas juntos y les queda un margen probalo por ahi te gusta si no lo dejas como esta.
> ● Pagá con tarjeta o en efectivo ● Envío gratis desde $ 2.500 ● Seguridad, de principio a fin ● Copyright © 1999-2022 MercadoLiebre S.R.L.
> 
> 2. Haciendo foco en los estilos del pie de página (Footer):
>    ● ¿El contenido de todos los artículos está centrado? = centralos un toque más y te queda god
> 
> ● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de 10 píxeles? = el icono si te falta el margen inferior no más
> 
> 3. ¿El sitio se adapta a distintas resoluciones de pantalla? = si se adapta bro solo tenes que agregare un poco más de estilo no más
> 4. ¿El sitio cuenta con un formulario de registro de usuarios? = si
> 5. ¿El sitio cuenta con un formulario de login?  = si
> 6. ¿Se muestran mensajes de error cuando un usuario coloca información
>    equivocada en un campo de los formularios? = si
> 7. ¿El search bar es un formulario?
> 8. ¿Se utilizan animaciones y propiedades de transición de CSS? = algo si solo agregale a los productos y botenes de los formularios
> 9. Para terminar el feedback, menciona algunas cosas que crees que tu
>    compañero hizo bien = toda la estructura esta bien bro solo te falta un poco mas de diseño, posicionamientos y estas.
> 
> 12.Por último, menciona algo que tu compañero podría mejorar = ya esta todo

**Comment by UrielBlanco7** [comment]
Arreglado
