### ISSUE TITLE
correcion 2

### ISSUE THREAD

**Issue by alexito2960** [UrielBlanco7/tienda-mercado-uriel#3]
![Imagen de WhatsApp 2023-02-13 a las 11 26 21](https://user-images.githubusercontent.com/121914750/218488084-b1adda53-d037-461d-9471-f12b9fa9baa3.jpg)

![Imagen de WhatsApp 2023-02-13 a las 11 26 21](https://user-images.githubusercontent.com/121914750/218488116-efb7f2af-37f0-4fc3-8611-93d8cf0d623e.jpg)

![Imagen de WhatsApp 2023-02-13 a las 11 27 25](https://user-images.githubusercontent.com/121914750/218488190-b4178957-35eb-4ccc-b18f-63f933d987fe.jpg)

mira bro te comparto como se ven en mi celu los producutos solo se tienen que ver uno no cuatro y la descripcion no se tiene que ver en caso si apretas.

La barra de navegacion no se tiene que ver en moviles "ofertas, vender, ayuda... etc" la imagen hay debajo tampoco eso seria más para decktops, te faltaria el logo del menu de hamburguesas que sea vea solamente debajo del logo y del "compra en cuotas y sin tarjeta de credito" eso seria para moviles y para decktops  no se tendria que ver el menu de hamburguesa solo asi como esta ahora.

FOOTER:

Eso lo podes hacer mas juntito como te dije todo  en la primera correcion.

Perdon bro por ponerte tantas cosas no te tomes a mal :( pero es para que te quede mejor y bueno espero puedas hacer esas cosas.

**Comment by UrielBlanco7** [comment]
arreglado
